set_property PACKAGE_PIN M19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN L18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports en_in]
set_property PACKAGE_PIN AB6 [get_ports en_in]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]







set_property PACKAGE_PIN U7 [get_ports {light_flowing[7]}]
set_property PACKAGE_PIN W5 [get_ports {light_flowing[6]}]
set_property PACKAGE_PIN W6 [get_ports {light_flowing[5]}]
set_property PACKAGE_PIN W7 [get_ports {light_flowing[4]}]
set_property PACKAGE_PIN V7 [get_ports {light_flowing[3]}]
set_property PACKAGE_PIN U5 [get_ports {light_flowing[2]}]
set_property PACKAGE_PIN U6 [get_ports {light_flowing[1]}]
set_property PACKAGE_PIN V4 [get_ports {light_flowing[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light_flowing[0]}]
set_property PACKAGE_PIN T19 [get_ports cc_highbit]
set_property PACKAGE_PIN P21 [get_ports cc_lowbit]
set_property PACKAGE_PIN R19 [get_ports cd_highbit]
set_property PACKAGE_PIN P20 [get_ports cd_lowbit]
set_property PACKAGE_PIN M20 [get_ports select0]
set_property PACKAGE_PIN N19 [get_ports select1]
set_property PACKAGE_PIN N20 [get_ports select2]
set_property PACKAGE_PIN M21 [get_ports select3]
set_property PACKAGE_PIN M22 [get_ports select4]
set_property PACKAGE_PIN N22 [get_ports select5]
set_property PACKAGE_PIN P22 [get_ports select6]
set_property PACKAGE_PIN R20 [get_ports select7]
set_property IOSTANDARD LVCMOS33 [get_ports cc_highbit]
set_property IOSTANDARD LVCMOS33 [get_ports cc_lowbit]
set_property IOSTANDARD LVCMOS33 [get_ports cd_highbit]
set_property IOSTANDARD LVCMOS33 [get_ports cd_lowbit]
set_property IOSTANDARD LVCMOS33 [get_ports select0]
set_property IOSTANDARD LVCMOS33 [get_ports select1]
set_property IOSTANDARD LVCMOS33 [get_ports select2]
set_property IOSTANDARD LVCMOS33 [get_ports select3]
set_property IOSTANDARD LVCMOS33 [get_ports select4]
set_property IOSTANDARD LVCMOS33 [get_ports select5]
set_property IOSTANDARD LVCMOS33 [get_ports select6]
set_property IOSTANDARD LVCMOS33 [get_ports select7]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
