# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.cache/wt [current_project]
set_property parent.project_path E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/blk_mem_gen_0/instruction_set.coe
add_files E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/data.coe
read_verilog -library xil_defaultlib {
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/alu.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/alu_mux.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/control_unit.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/new/data_memory.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/data_path.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/new/instruction_memory.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/ir.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/pc.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/reg_group.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/new/reg_group_mux.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/register.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/state_transition.v
  E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/imports/czy_2023.09.21/cpu.v
}
read_ip -quiet E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all e:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/constrs_1/new/led_flowing_constrains.xdc
set_property used_in_implementation false [get_files E:/Vivado2017/Lab/16_bits_multi_cycle_CPU/16_bits_multi_cycle_CPU.srcs/constrs_1/new/led_flowing_constrains.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cpu -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb"
